	#DEFINE GOFISH_APP_NAME 'GoFishClassic'
	#DEFINE GOFISH_APP_FILE  'GoFishClassic.app'
	#DEFINE GOFISH_VERSION '5.1.009'
	#DEFINE GOFISH_BUILDDATE 'September 30, 2023'
	#DEFINE GOFISH_DBUILDDATE Date(2023,9, 30)
	#DEFINE GOFISH_DOWNLOAD_URL 'https://raw.githubusercontent.com/VFPX/GoFishClassic/master/Source/Source.zip'
	#DEFINE GOFISH_VERSION_STRING_FOR_VERSION_FILE 'GoFishClassic - 5.1.009 - September 30, 2023 - 20230930'
	#DEFINE THOR_TOOL_NAME	'Thor_Tool_GoFishClassic'
	#DEFINE VERSON_FILE_URL	'https://github.com/VFPX/GoFishClassic/_GoFishClassicVersionFile.txt'
	#DEFINE VERSION_LOCAL_FILE 'GoFishClassicVersionFile.txt'
	#DEFINE GOFISH_HOME_PAGE 'https://github.com/VFPX/GoFishClassic'
